# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

significantRcpp <- function(smi1, T1, U1, B1) {
    .Call('MatrixCorrelation_significantRcpp', PACKAGE = 'MatrixCorrelation', smi1, T1, U1, B1)
}

